## CNN

#### Create Dataset

In [1]:
import dataset_generator

In [65]:
train, test = dataset_generator.create_dataset(num_mf=1000)

#### CNN

In [66]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
import numpy as np

# Define the CNN model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(20, 20, 1)),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(128, (3, 3), activation='relu'),
    Flatten(),
    Dense(128, activation='relu'),
    Dense(5, activation='softmax')  # Assuming 10 classes for classification
])

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Print the model summary
model.summary()



c:\Python311\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_12 (Conv2D)              │ (None, 18, 18, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_8 (MaxPooling2D)  │ (None, 9, 9, 32)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_13 (Conv2D)              │ (None, 7, 7, 64)       │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_9 (MaxPooling2D)  │ (None, 3, 3, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_14 (Conv2D)              │ (None, 1, 1, 128)      │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_4 (Flatten)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 128)            │        16,512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 5)              │           645 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 109,829 (429.02 KB)

 Trainable params: 109,829 (429.02 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
print((np.array(train[0][0]) == 0).astype(int))

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1]
 [1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1]
 [0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1]
 [0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0]
 [0 0 0 0 0 1 1 1 0 1 0 0 0 1 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 1 1 0 1 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0]]


In [23]:
print((np.array(train[0][1])))
train[0][0].show()

MinePatternType.V_SHAPE


In [79]:
#X_train = np.array([np.array(img[0]) == 0 for img in train])
#Y_train = np.array([img[1] for img in train])
#X_test = np.array([np.array(img) == 0 for img in test])

# Assuming images in 'train' are NumPy arrays:
X_train = np.array([np.array(img[0]) == 0 for img in train], dtype=bool).astype(int)
Y_train = np.array([img[1].value -1 for img in train])

X_test = np.array([np.array(img) == 0 for img in test], dtype=bool).astype(int)


In [80]:
Y_train.shape

(5000,)

In [69]:
# Extract integer values from Y_train
Y_train_int = np.array([label.value for label in Y_train])
print(Y_train_int)

[5 3 3 ... 1 5 3]


In [81]:
print(X_train.shape, X_train.dtype)  # Should be (num_samples, height, width) and float32
print(Y_train.shape, Y_train.dtype)  # Should be (num_samples,) and int32 or similar


(5000, 20, 20) int32
(5000,) int32


In [76]:
from tensorflow.keras.callbacks import EarlyStopping


In [77]:
early_stopping = EarlyStopping(
    monitor='val_loss',   # Monitor validation loss (or 'val_accuracy')
    patience=3,           # Stop after 3 epochs of no improvement
    restore_best_weights=True,  # Restore model weights from the best epoch
    verbose=1             # Print a message when stopping
)

# à ajouter dans les param du model.fit callbacks=[early_stopping]

In [82]:
# Train the model
model.fit(X_train, Y_train, epochs=10, batch_size=32, validation_split=0.2,callbacks=[early_stopping])

# Predict on test data
predictions = model.predict(X_test)

Epoch 1/10
125/125 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 0.6549 - loss: 0.8342 - val_accuracy: 0.9900 - val_loss: 0.0301
Epoch 2/10
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9899 - loss: 0.0324 - val_accuracy: 0.9960 - val_loss: 0.0138
Epoch 3/10
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.9969 - loss: 0.0129 - val_accuracy: 0.9990 - val_loss: 0.0068
Epoch 4/10
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.9994 - loss: 0.0041 - val_accuracy: 0.9960 - val_loss: 0.0149
Epoch 5/10
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.9987 - loss: 0.0027 - val_accuracy: 0.9960 - val_loss: 0.0098
Epoch 6/10
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.9980 - val_loss: 0.0042
Epoch 7/10
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 1.0000 - loss: 2.9060e-04 - val_accuracy: 0.9970 - val_loss: 0.0084
Epoch 8/10
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 1.0000 - loss: 8.0412e-04 - va

In [83]:
test[0]

In [84]:
predictions[0]

array([2.0872204e-09, 2.8788497e-10, 1.7644903e-07, 3.3153022e-12,
       9.9999988e-01], dtype=float32)

In [85]:
print(len(set(Y_train_int)))

5


In [87]:
# Evaluate on test data
test_loss, test_accuracy = model.evaluate(X_train, Y_train)
print(f"Test Accuracy: {test_accuracy * 100:.2f}%")


157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 1.0000 - loss: 4.9628e-04
Test Accuracy: 99.96%
