## CNN

#### Create Dataset

In [1]:
import dataset_generator

In [49]:
train, test = dataset_generator.create_dataset(num_mf=100000)

#### CNN

In [50]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
import numpy as np

# Define the CNN model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(20, 20, 1)),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(128, (3, 3), activation='relu'),
    Flatten(),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')  # Assuming 10 classes for classification
])

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Print the model summary
model.summary()



c:\Python311\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_9 (Conv2D)               │ (None, 18, 18, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_6 (MaxPooling2D)  │ (None, 9, 9, 32)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_10 (Conv2D)              │ (None, 7, 7, 64)       │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_7 (MaxPooling2D)  │ (None, 3, 3, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_11 (Conv2D)              │ (None, 1, 1, 128)      │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_3 (Flatten)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 128)            │        16,512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 110,474 (431.54 KB)

 Trainable params: 110,474 (431.54 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
print((np.array(train[0][0]) == 0).astype(float))
train[0][0].show()

[[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.

In [23]:
print((np.array(train[0][1])))
train[0][0].show()

MinePatternType.V_SHAPE


In [51]:
#X_train = np.array([np.array(img[0]) == 0 for img in train])
#Y_train = np.array([img[1] for img in train])
#X_test = np.array([np.array(img) == 0 for img in test])

# Assuming images in 'train' are NumPy arrays:
X_train = np.array([np.array(img[0]) == 0 for img in train], dtype=bool).astype(float)
#Y_train = np.array([img[1] for img in train])

X_test = np.array([np.array(img) == 0 for img in test], dtype=bool).astype(float)


In [52]:
# Extract integer values from Y_train
Y_train_int = np.array([label.value for label in Y_train])
print(Y_train_int)

[5 3 2 ... 5 4 1]


In [53]:
print(X_train.shape, X_train.dtype)  # Should be (num_samples, height, width) and float32
print(Y_train_int.shape, Y_train_int.dtype)  # Should be (num_samples,) and int32 or similar


(500000, 20, 20) float64
(500000,) int32


In [ ]:
from tensorflow.keras.callbacks import EarlyStopping


In [ ]:
early_stopping = EarlyStopping(
    monitor='val_loss',   # Monitor validation loss (or 'val_accuracy')
    patience=3,           # Stop after 3 epochs of no improvement
    restore_best_weights=True,  # Restore model weights from the best epoch
    verbose=1             # Print a message when stopping
)

# à ajouter dans les param du model.fit callbacks=[early_stopping]

In [54]:
# Train the model
model.fit(X_train, Y_train_int, epochs=10, batch_size=32, validation_split=0.2)

# Predict on test data
predictions = model.predict(X_test)

Epoch 1/10
12500/12500 ━━━━━━━━━━━━━━━━━━━━ 110s 9ms/step - accuracy: 0.9861 - loss: 0.0385 - val_accuracy: 0.9997 - val_loss: 0.0011
Epoch 2/10
12500/12500 ━━━━━━━━━━━━━━━━━━━━ 70s 6ms/step - accuracy: 0.9994 - loss: 0.0024 - val_accuracy: 0.9997 - val_loss: 0.0014
Epoch 3/10
12500/12500 ━━━━━━━━━━━━━━━━━━━━ 70s 6ms/step - accuracy: 0.9996 - loss: 0.0017 - val_accuracy: 0.9998 - val_loss: 8.3724e-04
Epoch 4/10
12500/12500 ━━━━━━━━━━━━━━━━━━━━ 65s 5ms/step - accuracy: 0.9997 - loss: 0.0012 - val_accuracy: 0.9999 - val_loss: 4.4640e-04
Epoch 5/10
12500/12500 ━━━━━━━━━━━━━━━━━━━━ 78s 6ms/step - accuracy: 0.9998 - loss: 8.6559e-04 - val_accuracy: 0.9998 - val_loss: 5.0202e-04
Epoch 6/10
12500/12500 ━━━━━━━━━━━━━━━━━━━━ 81s 6ms/step - accuracy: 0.9998 - loss: 8.2917e-04 - val_accuracy: 0.9998 - val_loss: 9.1975e-04
Epoch 7/10
12500/12500 ━━━━━━━━━━━━━━━━━━━━ 84s 7ms/step - accuracy: 0.9999 - loss: 7.8692e-04 - val_accuracy: 0.9998 - val_loss: 9.8419e-04
Epoch 8/10
12500/12500 ━━━━━━━━━━━━━

In [55]:
# Evaluate on test data
test_loss, test_accuracy = model.evaluate(X_train, Y_train_int)
print(f"Test Accuracy: {test_accuracy * 100:.2f}%")


15625/15625 ━━━━━━━━━━━━━━━━━━━━ 39s 2ms/step - accuracy: 0.9999 - loss: 4.2166e-04
Test Accuracy: 99.98%
